on:
  workflow_dispatch:
    inputs:
        tags:
          description: 'Manual run'
          required: false
          type: boolean
  schedule:
    - cron: '0 * * * *'

name: Check for changes

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

      # Use cURL to fetch the given URL, saving the response to `data.json`
      - name: Fetch data
        run: curl "https://api.steampowered.com/IPhysicalGoodsService/CheckInventoryAvailableByPackage/v1?origin=https:%2F%2Fstore.steampowered.com&input_protobuf_encoded=COOVNxICUEw%3D" -o data.json
          
      # Compare the response to the previous run, using a hash of the response as the cache key
      - name: Fetch Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: data.json
          key: ${{ hashFiles('data.json') }}
      
      # If there was not a cache hit (meaning the response changed), notify me via telegram
      # You could use a different notification action here, so long as you include the `if` condition below
      - name: Notify if data has changed
        uses: appleboy/telegram-action@master
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Steam Deck available
